### ISSUE TITLE
请教一下jingo问题

### ISSUE THREAD

**Issue by xhj967** [justbilt/wiki#1]
你好，从你的博客了解到jingo这个wiki
配置运行之后遇到几个问题：
1、新建的wiki页面显示搜索不到
2、所有wiki页面如何侧边栏标签分类导航呢？
能否帮忙解答一下呢，感谢！

**Comment by justbilt** [comment]
时间太久, 已然忘却了, 我最后也没有用 jingo. 他们也在 github 上有 repo, 你可以给他们开 issue 咨询下, 如果英文不好的话, 可以同时写中文 + Google 翻译后的译文, 他们可以看得懂的.

**Comment by justbilt** [comment]
地址: https://github.com/claudioc/jingo

**Comment by xhj967** [comment]
年前发的现在都没人理😭

**Comment by xhj967** [comment]
https://github.com/claudioc/jingo/issues/255
255是我开的。。不知道是不是英文不好，没描述清楚。。

**Comment by justbilt** [comment]
那你能在描述的详细一些吗? 我试了下, 好像可以搜索到呀.

![image](https://user-images.githubusercontent.com/3746991/53141219-480d2e00-35ca-11e9-89e6-9e913974df9c.png)

**Comment by justbilt** [comment]
你是不是没用通过 jingo 的界面去创建, 而是直接创建的文件

**Comment by xhj967** [comment]
知道原因了，不支持中文标题搜索。。
![qq 20190222111448](https://user-images.githubusercontent.com/46950578/53217785-68a1ba80-3694-11e9-8de5-3de52611f1ef.png)

![qq 20190222112948](https://user-images.githubusercontent.com/46950578/53217999-49eff380-3695-11e9-964a-55ff161f58de.png)

**Comment by xhj967** [comment]
然后还有2个问题：
1、右上角工具，列出所有页面显示不出来。
2、还有就是之前说到的想对文章分类😭

**Comment by justbilt** [comment]
文章分类估计你只能自己整理到一个 wiki 页面了, 列出所有界面的问题你可以看下这个 https://github.com/claudioc/jingo/issues/146

**Comment by justbilt** [comment]
jingo 是依靠 git 命令 `git ls-tree --name-only -r HEAD -- [docSubdir]/*.md` 来列出你所有的 md 文档的, 你在你的wiki 仓库目录执行下试试.

你可能需要把这些 md 都添加到你的 git 跟踪上

**Comment by xhj967** [comment]
感谢感谢 😄

**Comment by xhj967** [comment]
弃坑了，觉得页面分类还是很重要的，然后又用了这个，又遇到问题😭，烦请帮看看：）
https://github.com/gilbitron/Raneto/issues/293

**Comment by justbilt** [comment]
我觉得可能是适配的问题, demo 你把浏览器尺寸横向往小的拉, 也会跑到下面去, 你看下文档中有没有提到这点.

PS. 顺便吐槽下你的英文, 竟然比我还差. >_<

**Comment by xhj967** [comment]
![qq 20190226104756](https://user-images.githubusercontent.com/46950578/53383897-09091f00-39b4-11e9-91d4-e8c84a029973.png)


不像是浏览器问题啊，一样的配置demo显示正常呀
btw：英语是不好。。一直在下决心到放弃的循环中...😔

**Comment by justbilt** [comment]
那么会不会是数据的问题, 你的 wiki 数据太少或者结构不对, 你把 demo 的数据复制过来试试.

**Comment by xhj967** [comment]
demo数据也不对啊
